#!/usr/bin/env bash
# Bash script to automatically configure Ubuntu machine to requirements
apt-get update
apt-get -y install nginx
service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
string="\terror_page 404 /custom_404.html;\n\tlocation = /custom_404 {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}"
sed -i "/#error_page 404 \/404.html;/ a\\$string" /etc/nginx/sites-available/default
service nginx reload
service nginx restart