#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
COUNTER=1

while [ $COUNTER -le 20 ]; do
    echo $COUNTER
    
    if [ $COUNTER == 4 ]; then
        echo "bad luck from China"
    fi

    if [ $COUNTER == 9 ]; then
        echo "good luck from Japan"
    fi

    if [ $COUNTER == 17 ]; then
        echo "good luck from Italy"
    fi
    
    COUNTER=$((COUNTER+1))
done